### ISSUE TITLE
Enable setting of width / height or pass to Signal Slot

### ISSUE THREAD

**Issue by sfinnerWco** [theLine/typo3-lottie#7]
In our organization, we need to be able to set the width and heigth of a lottie animation. When I tried to manipulate the attributes by the SignalSlot, I recognized that the arguments width and height aren't passed to the Slot. 
While the corresponding part of the code for setting the width and height (in LottieRenderer.php) is commented, it would be great to have such an option.

Is it planned to enable the commented code for that again soon?
`// @TODO: Try to read the width/height and set it accordingly to prevent jumping of content
// $styles = [];
// if ($width) {
// 	$styles[] = 'width:'. (int)$width .'px';
// }
// if ($height) {
// 	$styles[] = 'height:'. (int)$height .'px';
// }`

Or would it be better to pass the arguments width and height to the SignalSlot? Then it would even be more customizable.

Also it would be better to set max-width and max-height instead of width and height due to responsive matters.

**Comment by theLine** [comment]
Sorry for my late response…

I've added some new features where the visual content shift will be eliminated (hopefully).
Additionally I've re-written the generation of the HTML output to use `TYPO3Fluid\Fluid\Core\ViewHelper\TagBuilder` which is a more robust solution when tinkering with HTML attributes.
Furthermore I've replaced the existing SignalSlot with a new one where all necessary arguments will be provided. Please have a look into commit 27d6f72c2cbf60bb62a8612c9626419253c53660 for that.
